### PR TITLE
Fix to work in place-with-space

### PR DESCRIPTION
**Pull request by mohawk2**
Also has 3-arg open, and clean up more files on `make clean`.

### CODE REVIEW

**Review by dk — APPROVED** [review]
this one is good, can be merged away

**Review by dk — CHANGES_REQUESTED** [review]
3-arg open is a good idea, thank you. I don't see a point though changing from open(FH) to open(my $fh) other than style, but I can live with that. However there's some namings that are lost, f ex open(PRIMADEF) vs open(my $fh), I'd like to keep original variable names where they make sense

**Review by dk — CHANGES_REQUESTED** [review]
The idea is solid but I don't understand why if I run new Makefile.PL under linux I get paths double-quoted. I think that while accounting for special characters is great, it should be done with care, no quoting if necessary . And the proper quote characters depending on the OS

(hint: there's $SHQUOTE variable available specifically for this)

**Comment by mohawk2** [comment]
> [bad5154](https://github.com/dk/Prima/pull/120/commits/bad515438ce211d34abd087c164707c9e8fd470d): this one is good, can be merged away

An approach you could do another time - if there's one or several commit(s) you're happy to accept, you could just cherry-pick it/them straight onto `master` and tell me to rebase this against that.

**Comment by mohawk2** [comment]
I believe I've addressed all the points you've raised. Please let me know if not!

**Comment by dk** [comment]
looks great, thank you!

**Pull request merged**
