### PR TITLE
Adding Spinner Animation Widget

### PR DESCRIPTION
**Pull request by MaxPerl**
Hey Dimitry,

Thanks again for all your help and your great suggestions.
I think I have mostly implemented. The only missing things are:

1) "Drawing the spinner so it covers the whole widget"
Thanks for your inspiration and help. But as I said I need some time for this. It can last some weeks or more, because I have not very much time to program at the moment. Sorry for that, but I think it does not hurry.

2) Using grey levels instead of black and white
I really think it is too hard for me :-S I am not a profi, just a hobby programmer and I am still learning Prima so your help would be very welcome...

Could you check again the active property. I liked the former version much more because you just need to call active to start or stop the widget without the need of the if...else construct. But uniformity of the usage of all Prima Widgets is more important and I don't understand Prima enough to judge which design is better with regard to the general design of Prima. Therefore please decide which way we want to go by yourself...

### CODE REVIEW

**Comment by dk** [comment]
Hi Max,

I value your contribution and your time, so I'd like to make myself clear on what drives me here. In no way I'm trying to make you do work you're not comfortable with. I'm sorry that suggestions I made are scaring you, so if you think you cannot do them, that's absolutely okay - I'll accept your contribution regardless and I can polish them myself later.

However, if you want to look at the hard parts as a sort of inspiration, a training of sorts, you're very much welcome to prove yourself on them, if you find such challenges interesting. And if you want to polish your skill on these tasks, I can definitely help you.

Sincerely,
  Dmitry

**Comment by dk** [comment]
I gave the module some loving hand, but didn't change any functionality except removing scaleFactor

**Comment by MaxPerl** [comment]
Dimitry,

No problem! You didn't scare me. But of course my abilities are limited. Therefore please feel absolutely free to change anything you want. Your Prima toolkit is such a great and fantastic work and so I am sure that your point of view is in any case the right way to implement a feature or widget.

I didn't understand your last post. Will someone else implement the "covering the whole widget" part? This would be great because for me it seems "prima facie" really difficult. If not I will bother about this the next weeks for myself. But it will last some weeks because I am really busy the next time...

And yes, all of your suggestions are a very welcome inspiration and training for me!

Best wishes,
Max

**Comment by dk** [comment]
Thank you! I just implemented these things myself. You're welcome to 'git pull' and take a look at how it works now, and have a go on them if you feel something can be improved. 

Thank you again for your contribution! 
Dmitry

**Pull request merged**
